version: "3"
services:
  app:
    container_name: api_airnose
    command: nodemon app.js  
    restart: always
    environment:
      - TZ=Asia/Bangkok
    build: .
    ports:
      - "80:80"
    links:
      - database
    volumes:
      - ./:/usr/src/app
    

  database:
    image: mongo:latest
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null #  