version: "3"
services:
  app:
    container_name: api_airnose
    restart: always
    environment:
      - TZ=Asia/Bangkok
    build: .
    ports:
      - "80:80"
    links:
      - database

  database:
    image: mongo
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"