version: "2"
services:
  app:
    container_name: api_airnose
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"